(async()=>{const q=new URLSearchParams(location.search);const slug=q.get('slug')||document.body.dataset.slug;const shots=u=>`https://s.wordpress.com/mshots/v1/${encodeURIComponent(u)}?w=1200`;const cfg={
'project-lamordia':{hero:shots('https://www.dndbeyond.com/posts/2250-now-loading-project_lamordia'),image1:shots('https://www.wargamer.com/dnd/project-lamordia'),caption1:'Deux regards sur la même réinvention : le teaser officiel et son traitement par la presse spécialisée.'},
'white-wolf':{hero:shots('https://www.paradoxinteractive.com/games/world-of-darkness/news/thank-you-renegade-game-studios'),image1:shots('https://www.worldofdarkness.com/'),caption1:'World of Darkness reste un univers de marques, de jeux et de communautés : la reprise éditoriale devra les faire parler d’une seule voix.'},
'dnd-en-mutation':{hero:shots('https://www.wargamer.com/dnd/magus-first-impressions'),image1:shots('https://www.dndbeyond.com/'),caption1:'D&D Beyond est devenu bien davantage qu’une bibliothèque numérique : c’est désormais un des lieux où la marque expérimente.'},
'the-one-ring':{hero:shots('https://www.backerkit.com/c/projects/free-league-publishing/the-one-ring-rpg-bestiary-gondor-campaign-updated-rules'),image1:shots('https://freeleaguepublishing.com/games/the-one-ring/'),caption1:'La gamme conserve une identité éditoriale très forte, même lorsqu’elle se prolonge dans de nouveaux suppléments et outils numériques.'},
'ghost-in-the-shell':{hero:'https://storage.ghost.io/c/50/c6/50c61f91-0165-4605-93bc-f8598149e466/content/images/size/w1200/2025/10/GitSTTRPG-Kickstarter-Announcement-News-FI.jpg',image1:shots('https://www.kickstarter.com/'),caption1:'Au-delà du chrome et des implants, l’enjeu est de transformer l’identité, la mémoire et l’institution en matière de jeu.'},
'critiques/torchbearer':{hero:'https://lefix.di6dent.fr/wp-content/uploads/2026/09/TorchbearerVF.png',image1:shots('https://lefix.di6dent.fr/archives/torchbearer-va-t-il-vous-apporter-la-lumiere-chronique/'),caption1:'La pression de Torchbearer vient autant de ses procédures que de son imaginaire de survie et d’expédition.'},
'critiques/blurred-lines':{hero:shots('https://lefix.di6dent.fr/archives/la-cite-de-la-peur-chronnique-de-blurried-lines/'),image1:shots('https://arkhane-asylum.fr/'),caption1:'Blurred Lines mise sur une économie de moyens qui laisse au joueur la charge de fabriquer les images de son propre giallo.'},
'critiques/saint-aymond':{hero:shots('https://lefix.di6dent.fr/archives/souvenir-de-vacances-a-st-aymond/'),image1:shots('https://www.ludika.fr/'),caption1:'Le Legs de Saint-Aymond préfère le village, les relations et la mémoire aux effets de système spectaculaires.'}
};const c=cfg[slug]||{};const publicUrl=`${location.origin}/oeil-de-jasra/numero-3/${slug}/`;const mount=document.getElementById('article');try{const html=await fetch(publicUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()});const doc=new DOMParser().parseFromString(html,'text/html');const main=doc.querySelector('main');if(!main)throw new Error('Article introuvable');main.querySelectorAll('[href]').forEach(el=>{const v=el.getAttribute('href');if(v&&!v.startsWith('#')&&!v.startsWith('mailto:')&&!v.startsWith('javascript:'))el.href=new URL(v,publicUrl).href});main.querySelectorAll('[src]').forEach(el=>{const v=el.getAttribute('src');if(v)el.src=new URL(v,publicUrl).href});mount.innerHTML=main.innerHTML;const hero=mount.querySelector('.article-hero');if(hero&&c.hero){hero.style.backgroundImage=`url("${c.hero}")`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center'}const prose=mount.querySelector('.prose');if(prose){const hs=[...prose.querySelectorAll('h2')];const insert=(url,caption,index)=>{if(!url||!hs.length)return;const fig=document.createElement('figure');fig.className='preview-figure';fig.innerHTML=`<img src="${url}" alt="" loading="lazy"><figcaption>${caption||''}</figcaption>`;(hs[Math.min(index,hs.length-1)]||hs[0]).insertAdjacentElement('beforebegin',fig)};insert(c.image1,c.caption1,2);insert(c.image2,c.caption2,5)}document.title=(doc.title||'Article')+' — Preview V6.3';}catch(e){mount.innerHTML=`<div class="loading">Impossible de charger l’article : ${e.message}</div>`}})();